/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachSessionsRouteImport } from './routes/coach.sessions'
import { Route as CoachProfilRouteImport } from './routes/coach.profil'
import { Route as CoachJoueursRouteImport } from './routes/coach.joueurs'
import { Route as CoachExercicesRouteImport } from './routes/coach.exercices'
import { Route as CoachDashboardRouteImport } from './routes/coach.dashboard'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppExercisesRouteImport } from './routes/_app.exercises'
import { Route as AppTestsIndexRouteImport } from './routes/_app.tests.index'
import { Route as AppSessionsIndexRouteImport } from './routes/_app.sessions.index'
import { Route as AppTestsSessionRouteImport } from './routes/_app.tests.session'
import { Route as AppSessionsSessionIdRouteImport } from './routes/_app.sessions.$sessionId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachSessionsRoute = CoachSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => CoachRoute,
} as any)
const CoachProfilRoute = CoachProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => CoachRoute,
} as any)
const CoachJoueursRoute = CoachJoueursRouteImport.update({
  id: '/joueurs',
  path: '/joueurs',
  getParentRoute: () => CoachRoute,
} as any)
const CoachExercicesRoute = CoachExercicesRouteImport.update({
  id: '/exercices',
  path: '/exercices',
  getParentRoute: () => CoachRoute,
} as any)
const CoachDashboardRoute = CoachDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CoachRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsIndexRoute = AppTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsSessionRoute = AppTestsSessionRouteImport.update({
  id: '/tests/session',
  path: '/tests/session',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/exercises': typeof AppExercisesRoute
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/exercices': typeof CoachExercicesRoute
  '/coach/joueurs': typeof CoachJoueursRoute
  '/coach/profil': typeof CoachProfilRoute
  '/coach/sessions': typeof CoachSessionsRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/tests/session': typeof AppTestsSessionRoute
  '/sessions/': typeof AppSessionsIndexRoute
  '/tests/': typeof AppTestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/exercises': typeof AppExercisesRoute
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/exercices': typeof CoachExercicesRoute
  '/coach/joueurs': typeof CoachJoueursRoute
  '/coach/profil': typeof CoachProfilRoute
  '/coach/sessions': typeof CoachSessionsRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/tests/session': typeof AppTestsSessionRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/tests': typeof AppTestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/exercises': typeof AppExercisesRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/profile': typeof AppProfileRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/exercices': typeof CoachExercicesRoute
  '/coach/joueurs': typeof CoachJoueursRoute
  '/coach/profil': typeof CoachProfilRoute
  '/coach/sessions': typeof CoachSessionsRoute
  '/_app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/_app/tests/session': typeof AppTestsSessionRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/_app/tests/': typeof AppTestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/exercises'
    | '/history'
    | '/home'
    | '/profile'
    | '/coach/dashboard'
    | '/coach/exercices'
    | '/coach/joueurs'
    | '/coach/profil'
    | '/coach/sessions'
    | '/sessions/$sessionId'
    | '/tests/session'
    | '/sessions/'
    | '/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/exercises'
    | '/history'
    | '/home'
    | '/profile'
    | '/coach/dashboard'
    | '/coach/exercices'
    | '/coach/joueurs'
    | '/coach/profil'
    | '/coach/sessions'
    | '/sessions/$sessionId'
    | '/tests/session'
    | '/sessions'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/coach'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/_app/exercises'
    | '/_app/history'
    | '/_app/home'
    | '/_app/profile'
    | '/coach/dashboard'
    | '/coach/exercices'
    | '/coach/joueurs'
    | '/coach/profil'
    | '/coach/sessions'
    | '/_app/sessions/$sessionId'
    | '/_app/tests/session'
    | '/_app/sessions/'
    | '/_app/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CoachRoute: typeof CoachRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/sessions': {
      id: '/coach/sessions'
      path: '/sessions'
      fullPath: '/coach/sessions'
      preLoaderRoute: typeof CoachSessionsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/profil': {
      id: '/coach/profil'
      path: '/profil'
      fullPath: '/coach/profil'
      preLoaderRoute: typeof CoachProfilRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/joueurs': {
      id: '/coach/joueurs'
      path: '/joueurs'
      fullPath: '/coach/joueurs'
      preLoaderRoute: typeof CoachJoueursRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/exercices': {
      id: '/coach/exercices'
      path: '/exercices'
      fullPath: '/coach/exercices'
      preLoaderRoute: typeof CoachExercicesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/dashboard': {
      id: '/coach/dashboard'
      path: '/dashboard'
      fullPath: '/coach/dashboard'
      preLoaderRoute: typeof CoachDashboardRouteImport
      parentRoute: typeof CoachRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tests/': {
      id: '/_app/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof AppTestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tests/session': {
      id: '/_app/tests/session'
      path: '/tests/session'
      fullPath: '/tests/session'
      preLoaderRoute: typeof AppTestsSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$sessionId': {
      id: '/_app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExercisesRoute: typeof AppExercisesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppHomeRoute: typeof AppHomeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
  AppTestsSessionRoute: typeof AppTestsSessionRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
  AppTestsIndexRoute: typeof AppTestsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExercisesRoute: AppExercisesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppHomeRoute: AppHomeRoute,
  AppProfileRoute: AppProfileRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
  AppTestsSessionRoute: AppTestsSessionRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
  AppTestsIndexRoute: AppTestsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CoachRouteChildren {
  CoachDashboardRoute: typeof CoachDashboardRoute
  CoachExercicesRoute: typeof CoachExercicesRoute
  CoachJoueursRoute: typeof CoachJoueursRoute
  CoachProfilRoute: typeof CoachProfilRoute
  CoachSessionsRoute: typeof CoachSessionsRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachDashboardRoute: CoachDashboardRoute,
  CoachExercicesRoute: CoachExercicesRoute,
  CoachJoueursRoute: CoachJoueursRoute,
  CoachProfilRoute: CoachProfilRoute,
  CoachSessionsRoute: CoachSessionsRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CoachRoute: CoachRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
