
-- Delete all existing data
DELETE FROM public.exercices;

-- Drop old columns
ALTER TABLE public.exercices
  DROP COLUMN IF EXISTS categorie,
  DROP COLUMN IF EXISTS difficulte,
  DROP COLUMN IF EXISTS duree_minutes,
  DROP COLUMN IF EXISTS description,
  DROP COLUMN IF EXISTS instructions,
  DROP COLUMN IF EXISTS image_url;

-- Drop old enum type
DROP TYPE IF EXISTS public.exercice_categorie;

-- Add new columns
ALTER TABLE public.exercices
  ADD COLUMN numero INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN bloc TEXT NOT NULL DEFAULT '',
  ADD COLUMN niveau TEXT NOT NULL DEFAULT 'Moyen',
  ADD COLUMN indicateur_cognitif TEXT NOT NULL DEFAULT '',
  ADD COLUMN alignement_test_digital TEXT NOT NULL DEFAULT '',
  ADD COLUMN objectif_cognitif TEXT NOT NULL DEFAULT '',
  ADD COLUMN materiel TEXT,
  ADD COLUMN tache_motrice TEXT NOT NULL DEFAULT '',
  ADD COLUMN stimulus_type TEXT NOT NULL DEFAULT '',
  ADD COLUMN stimulus_detail JSONB,
  ADD COLUMN regle_reponse TEXT,
  ADD COLUMN series INTEGER NOT NULL DEFAULT 3,
  ADD COLUMN duree_serie TEXT NOT NULL DEFAULT '',
  ADD COLUMN recuperation_secondes INTEGER NOT NULL DEFAULT 60,
  ADD COLUMN source_scientifique TEXT;

-- Seed 18 exercises
INSERT INTO public.exercices (numero, titre, bloc, niveau, indicateur_cognitif, alignement_test_digital, objectif_cognitif, materiel, tache_motrice, stimulus_type, stimulus_detail, regle_reponse, series, duree_serie, recuperation_secondes, source_scientifique) VALUES

(1, 'Plots Colorés : Prise en Hauteur ou Tacle Flash', 'Gardien de But', 'Moyen',
 'Attention Sélective + Contrôle Inhibiteur', 'Go/No-Go + Simon Task',
 'Entraîner l''attention sélective et le contrôle inhibiteur face à deux types de stimuli distincts (couleur vs flèche)',
 '2 ballons dans les coins du but, 3 plots de couleurs différentes espacés de 2.5m, smartphone sur support',
 'Jeu de jambes léger continu sur place en position de gardien prête (rebonds sur les orteils)',
 'COULEUR+FLÈCHE',
 '{"types":["COULEUR","FLÈCHE"],"couleurs_disponibles":["rouge","bleu","jaune"],"nb_plots":3,"intervalle_stimulus_sec":[5,8],"ecran_entre_stimuli":"noir","regle_couleur":"se déplacer vers le plot de cette couleur, sauter bras tendus vers le haut, revenir","regle_fleche":"se déplacer vers le ballon indiqué, le talonner au sol, revenir","pas_de_stimulus":"jeu de jambes continu"}',
 'COULEUR → se déplacer vers le plot, sauter bras tendus. FLÈCHE → talonner le ballon indiqué.',
 3, '2 min', 60, 'Schumacher et al. (2024)'),

(2, 'Jeu de Jambes Cercle : Flèche Directe / Couleur Inversée + Plongée', 'Gardien de But', 'Moyen',
 'Flexibilité Cognitive + Contrôle Inhibiteur', 'TMT B + Simon Task',
 'Entraîner la flexibilité cognitive et l''inhibition de la réponse dominante via alternance de règles directe/inversée',
 'Cercle au sol, 2 plots (gauche/droite), 2 ballons, smartphone sur support face au gardien',
 'Jeu de jambes stationnaire continu à l''intérieur du cercle (shuffle rapide)',
 'COULEUR+FLÈCHE',
 '{"types":["FLÈCHE","COULEUR"],"alternance":"aléatoire","regle_fleche":"réponse DIRECTE dans la direction indiquée","regle_couleur":"réponse dans la direction OPPOSÉE au plot de cette couleur","action_apres":"sortir du cercle, se positionner entre les plots, plonger pour contrôler le ballon, revenir dans le cercle"}',
 'FLÈCHE → direction directe. COULEUR → direction opposée. Puis plongée.',
 4, '90 s', 90, 'Schumacher et al. (2024) ; Haugan et al. (2025)'),

(3, 'Portes à 45° : Réaction Opposée à la Flèche', 'Gardien de But', 'Moyen',
 'Contrôle Inhibiteur', 'Simon Task',
 'Développer l''inhibition de la réponse dominante en allant à l''opposé de la flèche affichée',
 '2 portes (2 plots chacune) à 2-3m à 45° avant gauche et droit, smartphone face au gardien',
 'Position de gardien maintenue avec léger rebond dynamique continu',
 'FLÈCHE',
 '{"directions":["gauche","droite"],"intervalle":"aléatoire","regle":"FLÈCHE DROITE → aller vers la porte de GAUCHE. FLÈCHE GAUCHE → aller vers la porte de DROITE","enjeu_cognitif":"inhiber le réflexe naturel d''aller dans le sens de la flèche"}',
 'FLÈCHE DROITE → porte GAUCHE. FLÈCHE GAUCHE → porte DROITE.',
 3, '10 stimuli', 60, 'Huijgen et al. (2015) ; Haugan et al. (2025)'),

(4, 'Plongée sur Signal Flèche : Mécanique de Plongée', 'Gardien de But', 'Moyen',
 'Temps de Réaction', 'CRT',
 'Améliorer le temps de réaction moteur décisionnel en déclenchant une plongée dès l''apparition du signal',
 '2 ballons à distance de plongée (légèrement en angle avant), smartphone face au gardien',
 'Position de gardien prête avec rebond dynamique, regard vers l''écran',
 'FLÈCHE',
 '{"directions":["gauche","droite"],"intervalle_sec":[5,8],"regle":"Dès la flèche → plonger dans la direction indiquée. Initier en poussant le pied opposé. Atterrir sur le côté, une main sur le dessus du ballon, l''autre derrière."}',
 'Dès la flèche → plonger dans la direction indiquée.',
 3, '8 plongées', 90, 'Schumacher et al. (2024) ; Ando et al. (2001)'),

(5, 'Couverture Pied : Extension sur Signal Couleur', 'Gardien de But', 'Moyen',
 'Temps de Réaction + Attention Sélective', 'CRT',
 'Entraîner le temps de réaction et l''attention directionnelle via un signal couleur',
 '2 cônes (gauche et droite à 1m), smartphone face au gardien',
 'Position de gardien prête, bras écartés, léger rebond sur les orteils',
 'COULEUR',
 '{"nb_couleurs":2,"mapping":{"couleur_gauche":"lever pied gauche, étendre VERS L''AVANT derrière le cône, orteil fléchi vers le haut","couleur_droite":"idem côté droit"},"precision":"extension vers l''avant uniquement, pas latéralement","intervalle_sec":[4,6]}',
 'Couleur gauche → extension pied gauche. Couleur droite → extension pied droit.',
 3, '12 stimuli', 60, 'Schumacher et al. (2024)'),

(6, 'Pair / Impair : Poteau Avant vs Ligne de But', 'Gardien de But', 'Moyen',
 'Mémoire de Travail + Flexibilité Cognitive', 'N-Back / TMT',
 'Développer la mémoire de travail et le traitement numérique rapide via règle pair/impair',
 'Ballon A (poteau avant droite), Ballon B (ligne de but gauche), smartphone face au gardien',
 'Position de gardien dynamique, léger footwork sur place',
 'NOMBRE',
 '{"plage_nombres":[1,9],"intervalle_sec":[5,7],"regle":"NOMBRE PAIR → plonger vers Ballon A (poteau avant). NOMBRE IMPAIR → plonger vers Ballon B (ligne de but). Calculer mentalement la parité, faire le premier pas immédiatement, atterrir sur le côté, sécuriser la balle."}',
 'PAIR → Ballon A (poteau avant). IMPAIR → Ballon B (ligne de but).',
 3, '10 stimuli', 90, 'Vestberg et al. (2017) ; Schumacher et al. (2024)'),

(7, '4 Cônes Colorés avec Ballons : Positionnement et Plongée', 'Gardien de But', 'Moyen',
 'Anticipation Perceptuelle + Temps de Réaction', 'Anticipation Task + CRT',
 'Entraîner le positionnement proactif et le TR décisionnel via signal couleur + flèche directionnelle',
 '4 cônes de couleurs différentes espacés de 3-4 yards, un ballon devant chaque cône, smartphone face au gardien',
 'Position de gardien prêt avec footwork dynamique, regard alterné écran/terrain',
 'COULEUR+FLÈCHE',
 '{"nb_cones":4,"signal":"COULEUR du cône ciblé + FLÈCHE verticale (avant = avancer, arrière = reculer)","action":"avancer ou reculer rapidement vers le ballon du cône ciblé, se stabiliser, plonger en angle avant, atterrir sur le côté une main sur le dessus et l''autre derrière, revenir en position de départ","nb_stimuli":12}',
 'COULEUR → identifier le cône. FLÈCHE → avancer ou reculer. Puis plonger.',
 3, '12 stimuli', 90, 'Van Maarseveen et al. (2018) ; Haugan et al. (2025)'),

(8, 'Jonglerie + Réaction Périphérique', 'Attention', 'Moyen → Élevé',
 'Attention Divisée', 'Go/No-Go',
 'Entraîner l''attention divisée et la réaction périphérique simultanément à une tâche motrice continue',
 'Ballon de foot, smartphone sur support à 45° du champ visuel (côté, pas devant)',
 'Jonglerie continue, maintien du ballon en l''air en continu',
 'FLASH',
 '{"couleurs":["rouge","vert"],"intervalle_sec":[4,7],"position_ecran":"45° côté champ visuel","regle":"Dès détection du flash en vision périphérique → toucher l''écran SANS perdre la jonglerie","progression":"augmenter le nombre de balles après 4 semaines"}',
 'Flash détecté → toucher l''écran sans perdre la jonglerie.',
 2, '4 min', 60, 'Schumacher, Reer & Braumann (2020)'),

(9, 'Carré Coloré : Attention Réactive (4 Plots)', 'Attention', 'Faible',
 'Attention Sélective', 'CRT',
 'Entraîner l''attention sélective et le temps de réaction de choix en situation de conduite de balle',
 '4 plots colorés disposés en carré N/S/E/O (3-4m de côté), smartphone face au joueur',
 'Tapotements dynamiques du ballon au centre du carré',
 'COULEUR',
 '{"nb_plots":4,"disposition":"carré N/S/E/O, 3-4m de côté","intervalle_sec":[5,7],"ecran_entre_stimuli":"noir","regle":"Conduire vers le plot de la couleur affichée, le contourner, revenir au centre, reprendre les tapotements"}',
 'Couleur affichée → conduire vers le plot correspondant, contourner, revenir.',
 3, '2 min', 60, 'Schumacher et al. (2024) ; Mao et al. (2024)'),

(10, 'Passes Mur + Épaule Check : Couleur/Flèche', 'Attention', 'Moyen',
 'Attention Sélective', 'CRT',
 'Développer l''attention sélective et le TR de choix en combinant passe et scanning visuel actif',
 'Mur pour passes, 2-3 plots colorés, smartphone posé dans le dos du joueur (visible uniquement lors du check)',
 'Passes continues contre le mur, épaule check alterné gauche/droite après chaque passe',
 'COULEUR+FLÈCHE',
 '{"consultation":"uniquement lors du check (retournement)","regle_couleur":"conduire vers le plot de cette couleur","regle_fleche_verte":"partir dans la direction indiquée","pas_de_stimulus":"passes continues"}',
 'Check → COULEUR = plot correspondant. FLÈCHE verte = direction indiquée.',
 3, '3 min', 60, 'Pedrosa & Tavares (2025) ; Casella et al. (2022)'),

(11, 'Échelle de Vitesse : Couleur de Sortie', 'Attention', 'Moyen → Élevé',
 'Attention Sélective', 'CRT',
 'Améliorer l''attention sélective décisionnelle et le TR de choix en sortie de tâche motrice intense',
 'Échelle de vitesse, 4 cônes colorés à 3m, smartphone face au joueur',
 'Exercices d''échelle de vitesse en boucle continue (in-in-out-out ou ickey shuffle) à vitesse maximale',
 'COULEUR',
 '{"nb_cones":4,"distance_cones_m":3,"moment_consultation":"à la sortie de l''échelle, lever les yeux vers l''écran","timing":"aléatoire","regle_couleur":"sprint immédiat vers le cône de cette couleur","ecran_noir":"sprint ligne droite"}',
 'Sortie échelle → couleur = sprint vers le cône. Écran noir = sprint droit.',
 4, '8 passages', 60, 'Sudesan Jothi et al. (2025)'),

(12, 'Ballon Cible : Fond Signal (Vert Direct / Rouge Inversé)', 'Inhibition', 'Faible → Moyen',
 'Contrôle Inhibiteur', 'Simon Task',
 'Développer la mémoire de travail et le contrôle inhibiteur via identification simultanée flèche + couleur de fond',
 'Plots colorés, ballons, smartphone face au joueur',
 'Identifier le stimulus, prendre la balle de sa place récente, la déposer au plot cible',
 'COULEUR+FLÈCHE',
 '{"stimulus":"flèche directionnelle avec background rouge ou vert","intervalle":"aléatoire","regle_fond_vert":"prendre la balle et la déposer au plot correspondant à la DIRECTION de la flèche","regle_fond_rouge":"prendre la balle et la déposer au plot OPPOSÉ à la direction de la flèche"}',
 'Fond VERT → direction de la flèche. Fond ROUGE → direction opposée.',
 3, '3 min', 75, 'Huijgen et al. (2015) ; Haugan et al. (2025)'),

(13, 'Couleur/Flèche : Réponse Opposée', 'Inhibition', 'Faible → Moyen',
 'Contrôle Inhibiteur', 'Simon Task',
 'Développer le contrôle inhibiteur en bloquant la réponse automatique pour sélectionner l''alternative correcte',
 'Plots colorés, smartphone face au joueur',
 'Se déplacer vers le plot cible selon la règle',
 'COULEUR+FLÈCHE',
 '{"types_alternants":["COULEUR","FLÈCHE"],"regle_couleur":"aller vers le plot de la MÊME couleur","regle_fleche":"aller vers le plot OPPOSÉ à la direction de la flèche"}',
 'COULEUR → même couleur. FLÈCHE → direction opposée.',
 3, '3 min', 75, 'Schumacher et al. (2024) ; Haugan et al. (2025)'),

(14, 'Mémoire de Travail + Conduite de Balle', 'Mémoire de Travail', 'Moyen → Élevé',
 'Mémoire de Travail', 'N-Back',
 'Développer la mémoire de travail et la mise à jour de l''information en temps réel via règle pair/impair cumulative',
 'Smartphone face au joueur, 2 plots latéraux gauche/droite',
 'Conduite de balle entre position centrale et plots latéraux, demi-tour dynamique à chaque retour',
 'NOMBRE',
 '{"plage_nombres":[1,99],"premier_stimulus":{"pair":"conduire vers plot DROIT","impair":"conduire vers plot GAUCHE"},"stimulus_suivants":{"regle":"additionner mentalement le nouveau nombre au précédent","resultat_pair":"aller à droite","resultat_impair":"aller à gauche"},"presentation":"aléatoire à chaque passage"}',
 '1er nombre : pair→droite, impair→gauche. Suivants : additionner au précédent, résultat pair→droite, impair→gauche.',
 3, '3 min', 75, 'Vestberg et al. (2017) ; Schumacher et al. (2024) ; Haugan et al. (2025)'),

(15, 'Jonglerie + Addition Verbale', 'Mémoire de Travail', 'Moyen → Élevé',
 'Mémoire de Travail', 'N-Back',
 'Développer la mémoire de travail et le traitement mental sous contrainte motrice via addition successive verbalisée',
 'Ballon de foot, smartphone face au joueur',
 'Jonglerie continue (pied dominant puis alterné), sans interruption',
 'NOMBRE',
 '{"plage_nombres":[2,9],"intervalle_sec":[3,4],"regle":"additionner mentalement chaque nouveau nombre avec le précédent et annoncer le résultat à voix haute","exemple":["3 → mémoriser","5 → annoncer 8","2 → annoncer 7 (5+2)","4 → annoncer 6 (2+4)"]}',
 'Additionner chaque nombre au précédent et annoncer le résultat à voix haute.',
 3, '2 min', 60, 'Baddeley (2000) ; Vestberg et al. (2017)'),

(16, 'Jonglerie + Association Nombre-Position', 'Mémoire de Travail', 'Moyen',
 'Mémoire de Travail Visuospatiale', 'N-Back',
 'Développer la mémoire de travail visuospatiale et l''association stimulus-position en double tâche',
 '4 plots formant un carré, ballon de foot, smartphone face au joueur',
 'Jonglerie continue au centre du carré, puis conduite vers plot ciblé',
 'NOMBRE',
 '{"setup":"Avant le début : chaque plot est associé à un numéro (1 à 4), annoncé au joueur","plage_nombres":[1,4],"intervalle_sec":[4,6],"regle":"Dès l''affichage du nombre → arrêter la jonglerie, identifier le plot correspondant, conduire la balle vers ce plot, effectuer un demi-tour autour du plot, revenir au centre, reprendre la jonglerie"}',
 'Nombre affiché → conduire vers le plot correspondant, demi-tour, revenir.',
 3, '3 min', 75, 'Vestberg et al. (2017) ; Haugan et al. (2025)'),

(17, 'Carré Coloré avec Balle de Tennis', 'Inhibition/Flexibilité', 'Faible → Moyen',
 'Contrôle Inhibiteur + Flexibilité Cognitive', 'Simon Task',
 'Développer le contrôle inhibiteur et la flexibilité cognitive via règle conditionnelle à deux dimensions (direction + couleur de fond)',
 '4 plots colorés en carré, balles de tennis, smartphone face au joueur',
 'Identifier direction + fond, se déplacer vers le plot correct, prendre la balle de tennis, la déposer sur le plot cible, revenir au centre',
 'COULEUR+FLÈCHE',
 '{"stimulus":"flèche directionnelle avec arrière-plan vert ou rouge","intervalle_sec":[3,5],"regle_fond_vert":"aller dans la MÊME direction que la flèche","regle_fond_rouge":"aller dans la direction OPPOSÉE à la flèche","action":"prendre la balle de tennis → déposer sur le plot cible → revenir immédiatement au centre"}',
 'Fond VERT → même direction. Fond ROUGE → direction opposée.',
 3, '3 min', 75, 'Roca et al. (2011)'),

(18, 'Passes Mur : Set-Shifting Forme/Couleur', 'Flexibilité Cognitive', 'Faible → Moyen',
 'Flexibilité Cognitive', 'TMT B',
 'Entraîner le set-shifting en basculant entre deux dimensions de réponse concurrentes (forme vs couleur) selon un mot-clé contextuel',
 'Mur pour passes, 2-4 plots, smartphone face au joueur (consulté lors du check)',
 'Passes continues contre le mur avec épaule check alterné gauche/droite après chaque passe',
 'FORME+COULEUR',
 '{"sequence":"mot-clé affiché D''ABORD (FORME ou COULEUR), puis stimulus combiné (ex. carré rouge)","intervalle_sec":5,"dimension_active":"alterne aléatoirement","regle_FORME":"répondre selon la FORME du stimulus (ignorer la couleur)","regle_COULEUR":"répondre selon la COULEUR du stimulus (ignorer la forme)","exemple":"FORME + carré rouge → plot carré. COULEUR + carré rouge → plot rouge","enjeu":"ignorer la dimension non pertinente même si elle suggère la réponse opposée"}',
 'Mot-clé FORME → répondre selon la forme. Mot-clé COULEUR → répondre selon la couleur.',
 3, '10 stimuli', 60, 'Roca et al. (2011)');
